[package]
name = "bunku"
version = "0.1.0"
edition = "2021"

[dependencies]
k8s-openapi = { version = "0.23", features = ["latest"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
