apiVersion = "v1beta1"

[metadata]
name = "podinfo"

[containers.app]
image = "docker.io/stefanprodan/podinfo:6.7.1"

[service.ports.http]
port = 9898
protocol = "TCP"

[resources.dns]
type = "dns"
params = {
  subdomain = "podinfo"
}

[resources.route]
type = "route"
params = {
  host= "${resources.dns.host}"
  path = "/"
  port = "http"
}
