apiVersion = "v1beta1"

[metadata]
name = "hello-world"

[containers.app]
image = "docker.io/library/busybox:1.36"
command = ["/bin/sh"]
args = ["-c", "while true; do echo Hello World!; sleep 5; done"]
