[controllers.main]
enabled = true
type = "deployment"
replicas = 1

[controllers.main.containers.app]
image = "docker.io/library/busybox:1.36"
command = ["/bin/sh"]
args = ["-c", "while true; do echo Hello World!; sleep 5; done"]
