[controllers.main]
enabled = true
type = "deployment"
replicas = 1

[controllers.main.containers.app]
image = "docker.io/library/nginx:1.27.3"

[controllers.main.containers.app.ports.http]
containerPort = 80
protocol = "TCP"

[service.main]
enabled = true
type = "ClusterIP"
controller = "main"

[service.main.ports.http]
port = 80
targetPort = 80
protocol = "TCP"
